modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/LordGrimmauld/discordchat/issues"

[[mods]]
    modId="discordchat"
    version="${file.jarVersion}"
    displayName="Dicord Chat"
    #updateJSONURL=""
    authors="Grimmauld"
    description='''
Discord MC server chat integration'''

[[dependencies.discordchat]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.discordchat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"